spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
server.port=${PORT:${SERVER_PORT:8080}}
app.data-root=${DATA_ROOT:data}
app.upload-root=${APP_UPLOAD_ROOT:${app.data-root}/uploads}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
